apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  ports:
    - port: 3000
  selector:
    app: auth-service
    tier: frontend
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-service
        tier: frontend
    spec:
      containers:
      - image: ppeerttu/auth-service:latest
        name: auth-service
        ports:
        - containerPort: 3000
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        env:
        - name: POSTGRES_DB
          value: auth-service
        - name: POSTGRES_USER
          value: auth-service
        - name: POSTGRES_PASSWORD
          value: auth-service
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_HOST
          value: auth-db-postgresql.default.svc.cluster.local
        - name: JWT_AUDIENCE
          value: instagram-clone
        - name: JWT_ISSUER
          value: auth-service
        - name: JWT_ACCESS_SECRET
          value: grazyfoxjumpsoverlazyfrog
        - name: JWT_REFRESH_SECRET
          value: grazyfoxjumpsoverlazyfroggrazyfoxjumpsoverlazyfrog
        - name: NODE_ENV
          value: production
        - name: CONSUL_HOST
          value: hashicorp-consul-server.default.svc.cluster.local
        - name: GRPC_PORT
          value: "3000"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: redis-master.default.svc.cluster.local
        - name: KAFKA_SERVERS
          value: kafka.default.svc.cluster.local:9092
        - name: KAFKA_ACCOUNT_TOPIC
          value: accounts
        - name: CONSUL_ENABLED
          value: "false"

