version: "3"

services:
  user-service:
    container_name: user-service-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/src
      - /src/env
    ports:
      - "8080:8080"
    depends_on:
      - user-db
    networks:
      - ig-clone-dev
    env_file:
      - .db.env
    environment:
      POSTGRES_HOST: user-db-dev
      KAFKA_SERVERS: kafka-dev:9092
      KAFKA_ACCOUNTS_TOPIC: accounts
      KAFKA_USERS_TOPIC: users
      KAFKA_CONSUMER_GROUP: user-service
      CONSUL_HOST: consul-dev

  user-db:
    container_name: user-db-dev
    image: postgres:11-alpine
    volumes:
      - user-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ig-clone-dev
    env_file:
      - .db.env

  user-migrations:
    container_name: user-migrations-dev
    image: amacneil/dbmate
    command: migrate
    volumes:
      - ./db:/db
    networks:
      - ig-clone-dev
    depends_on:
      - user-db
    environment:
      DATABASE_URL: ${DATABASE_URL}

networks:
  ig-clone-dev:
    external:
      name: ig-clone-dev

volumes:
  user-data-dev:
    external: true
