apiVersion: v1
kind: Service
metadata:
  name: image-service
  labels:
    app: image-service
spec:
  ports:
    - port: 3000
  selector:
    app: image-service
    tier: frontend
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-data-pv-claim
spec:
  storageClassName: efs-sc
  # storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  labels:
    app: image-service
spec:
  selector:
    matchLabels:
      app: image-service
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: image-service
        tier: frontend
    spec:
      volumes:
      - name: image-persistent-storage
        persistentVolumeClaim:
          claimName: image-data-pv-claim
      containers:
      - image: ppeerttu/image-service:1.0.0-SNAPSHOT
        name: image-service
        ports:
        - containerPort: 3000
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: image-persistent-storage
          mountPath: /app/image-data
        env:
        - name: GRPC_HOST
          value: 0.0.0.0
        - name: GRPC_PORT
          value: "3000"
        - name: IMAGE_DATA_DIR
          value: /app/image-data
        - name: CONSUL_HOST
          value: consul-server.default.svc.cluster.local
        - name: CONSUL_PORT
          value: "8500"
        - name: CONSUL_ENABLED
          value: "false"
        - name: MONGO_HOST
          value: mongodb.default.svc.cluster.local
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DATABASE
          value: images
        - name: MONGO_USER
          value: image-service
        - name: MONGO_PASSWORD
          value: image-service
        - name: IMAGES_COLLECTION
          value: image_meta
        - name: LIKES_COLLECTION
          value: image_likes
        - name: KAFKA_SERVERS
          value: kafka.default.svc.cluster.local:9092
        - name: IMAGES_TOPIC
          value: images
        - name: USERS_TOPIC
          value: users
        - name: KAFKA_CONSUMER_GROUP
          value: image-service
